import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import decodeTile from "../mltDecoder";
import type FeatureTable from "../vector/featureTable";
import { GEOMETRY_TYPE } from "../vector/geometry/geometryType";
import type { GeometryZ, PointZ } from "../vector/geometry/geometryVector";

// Fixture generated by the Rust encoder. Regenerate with:
//   cargo test -p mlt-core --lib -- --ignored generate_ts_3d_fixture --nocapture
const FIXTURE = path.resolve(__dirname, "__fixtures__/geom_z.mlt");

function decode(): FeatureTable[] {
    const bytes = new Uint8Array(readFileSync(FIXTURE));
    // idWithinMaxSafeInteger=false to match the synthetic suite's behaviour.
    return decodeTile(bytes, undefined, false);
}

function tableNamed(name: string): FeatureTable {
    const table = decode().find((t) => t.name === name);
    if (!table) {
        throw new Error(`layer "${name}" not found`);
    }
    return table;
}

/** First feature's geometry as a 3D geometry, asserting the layer is 3D. */
function geometry3d(name: string): GeometryZ {
    const table = tableNamed(name);
    expect(table.numDimensions).toBe(3);
    return table.getFeatures()[0].geometry as GeometryZ;
}

const xyz = (p: PointZ): number[] => [p.x, p.y, p.z];

// Stored Z is centimeters; the decoder returns meters (z_grid * 0.01). Expected
// Z values are written as `<grid> * 0.01` so they match the decoder's exact
// IEEE result (e.g. 30 * 0.01 === 0.30000000000000004).
const M = 0.01;

describe("MLT Decoder - 3D (GeometryZ)", () => {
    it("decodes every layer as 3D", () => {
        for (const table of decode()) {
            expect(table.numDimensions).toBe(3);
        }
    });

    it("decodes a 3D Point", () => {
        const geom = geometry3d("point_z");
        expect(geom.type).toBe(GEOMETRY_TYPE.POINT);
        expect(xyz(geom.coordinates[0][0])).toEqual([10, 20, 30 * M]);
    });

    it("decodes a 3D LineString", () => {
        const geom = geometry3d("linestring_z");
        expect(geom.type).toBe(GEOMETRY_TYPE.LINESTRING);
        expect(geom.coordinates[0].map(xyz)).toEqual([
            [1, 2, 3 * M],
            [4, 5, 6 * M],
            [7, 8, 9 * M],
        ]);
    });

    it("decodes a 3D Polygon (closing vertex re-added)", () => {
        const geom = geometry3d("polygon_z");
        expect(geom.type).toBe(GEOMETRY_TYPE.POLYGON);
        expect(geom.coordinates[0].map(xyz)).toEqual([
            [0, 0, 1 * M],
            [10, 0, 2 * M],
            [10, 10, 3 * M],
            [0, 10, 4 * M],
            [0, 0, 1 * M],
        ]);
    });

    it("decodes a 3D MultiPoint", () => {
        const geom = geometry3d("multipoint_z");
        expect(geom.type).toBe(GEOMETRY_TYPE.MULTIPOINT);
        expect(geom.coordinates.map((part) => xyz(part[0]))).toEqual([
            [1, 2, 3 * M],
            [4, 5, 6 * M],
        ]);
    });
});
